Fix for:
org.apache.commons.lang.UnhandledException: Plugin RegionShop v2.1.1 generated an exception while executing task 78
	at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at org.bukkit.craftbukkit.v1_6_R3.CraftWorld.getEntities(CraftWorld.java:542)
	at com.geNAZt.RegionShop.Data.Tasks.DisplayItemOverChest.run(DisplayItemOverChest.java:33)
	at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)